on:
  push:
    branches: master

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CENSUS_API_KEY: ${{ secrets.CENSUS_KEY }}
      R_LIBS_USER: ~/Library/Application Support/renv
      CACHE-NAME: refresh_cache
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 3)
        shell: Rscript {0}

      - name: Install package
        run: |
          R CMD INSTALL .
          install.packages("sf")

      - name: Establish git credentials
        run: |
          install.packages("usethis")
          usethis::use_git_config(user.name = "David Kane", user.email = "dave.kane@gmail.com")
        shell: Rscript {0}

      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
