on:
  push:
    branches: master

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    env:
      R_COMPILE_AND_INSTALL_PACKAGES: never
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CENSUS_API_KEY: ${{ secrets.CENSUS_KEY }}
      R_LIBS_USER: ~/Library/Application Support/renv
      CACHE-NAME: refresh_cache
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install imagemagick@6
          brew install libgit2
          brew install libcurl
          brew install curl
        shell: Rscript {0}
      
     
      - uses: r-lib/actions/setup-renv@v2
      
      - uses: r-lib/actions/setup-r@v2
      
      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Install package
        run: |
          R CMD INSTALL .

      - name: Establish git credentials
        run: |
          install.packages("usethis")
          usethis::use_git_config(user.name = "David Kane", user.email = "dave.kane@gmail.com")
        shell: Rscript {0}

      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
