# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_ACTIVATE_PROJECT: TRUE
      R_LIBS_USER: ~/Library/Application Support/renv
      GITHUB_ACTION: TRUE
      CENSUS_API_KEY: ${{ secrets.CENSUS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config
          brew install gdal
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::renv
            any::rcmdcheck
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/renv.lock
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('renv.lock') }}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}


