# Start with https://github.com/r-lib/actions, with https://github.com/features/actions
# as general background. 

# For help debugging build failures open an issue on the RStudio community 
# with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions

# Key point when considing r2u: 

# r2u is an apt repo, which via bspm becomes used 
# "automagically" via standard R calls of install.packages() and alike. 
# That last part is important: package installations that do not use install.packages() 
# (such as the RStudio GUI, renv, rig, ...) do not benefit from install.packages() 
# calling apt for you, and cannot take advantage of r2u.

# So, we can use renv or r2u but not both.

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      R_COMPILE_AND_INSTALL_PACKAGES: never
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_ACTIVATE_PROJECT: TRUE
      R_LIBS_USER: ~/Library/Application Support/renv
      GITHUB_ACTION: TRUE
      CENSUS_API_KEY: ${{ secrets.CENSUS_KEY }} 
      R_KEEP_PKG_SOURCE: no
      
# Got the renv setup advice from: https://github.com/r-lib/actions/tree/v2/setup-renv. 
# But not sure if this is necessary nor how to use it. 
      
    steps:
      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install gdal
          brew install imagemagick@6
          brew install libgit2
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - uses: r-lib/actions/setup-pandoc@v2    
      
      
      # Very annoying that just compiling the packages does not work easily. Would probably
      # be better off using unbuntu and r2u. In the meantime, we need to hack arnound so
      # that problematic packages like sf compile. We definiately need gdal to be
      # installed ahead of time.
      
      # Perhaps useful: https://rstudio.github.io/renv/articles/ci.html
 
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2
          extra-packages: |
            any::renv
            any::rcmdcheck
          needs: |
            website
            coverage
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
