# Start with https://github.com/r-lib/actions, with https://github.com/features/actions
# as general background. 
# Explore r2u, may be superior to caching.
# We can use renv or r2u but not both.

# Workflow will run on push or pull request.
# Can specify branches if we expand past a master branch.

on:
  push:
  pull_request:

# Just the name of the workflow.

name: R-CMD-check
jobs:
  R-CMD-check:

    # Runs on ubuntu 
    # Can be run on macOS or Windows but ubuntu seems to work better.

    runs-on: ubuntu-latest

    # Environmental variables:
    # You can use environment variables to store information 
    # that you want to reference in your workflow. 
    # You reference environment variables within a 
    # workflow step or an action, and the variables are interpolated on the runner machine that runs your workflow

    env:

      # Forces binary download instead of building packages from source.

      R_COMPILE_AND_INSTALL_PACKAGES: never
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_ACTIVATE_PROJECT: TRUE
      R_LIBS_USER: ~/Library/Application Support/renv
      GITHUB_ACTION: TRUE

      # Census api key is not working, not sure how to embed it.
      # We have already defined it as a secret in github

      CENSUS_API_KEY: ${{ secrets.CENSUS_KEY }} 

      # Not sure why but this variable seems to improve workflow.

      R_KEEP_PKG_SOURCE: yes
      
# Got the renv setup advice from: https://github.com/r-lib/actions/tree/v2/setup-renv. 
# But not sure if this is necessary nor how to use it. 
      
    steps:

      # All these "uses:" steps refer to pre-built yaml files 
      # that people have already built, making our lives easier!
      # See the following ReadMe file for information on each command.
      # https://github.com/r-lib/actions

      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@master
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
    
          # Cache is version 1 by default.
          # If you need to clear cache and create new one,
          # change cache-version to 2 for only one commit.
          # Change it back to 1 for the commit after that.
  
          cache-version: 1
  
      # Running rcmdcheck below, shows us an error whenver the workflow
      # says "error".
      # You can do the check inside rstduio itself by either clicking
      # "check" in the build tab or running the rcmdcheck() function.
      # This yaml files will run rcmdcheck in the cloud.
  
      - name: Check
        run: |
          install.packages("rcmdcheck")
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
