# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_ACTIVATE_PROJECT: TRUE
      R_LIBS_USER: ~/Library/Application Support/renv
      GITHUB_ACTION: TRUE
      CENSUS_API_KEY: ${{ secrets.CENSUS_KEY }}
      CACHE-NAME: refresh_cache
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config
          brew install gdal
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 3
          extra-packages: |
            any::renv
            any::rcmdcheck
      - name: Cache R packages
        id: cache_new
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.2-1-build-{{env.cache-name}}-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-4.2-1
      - if: ${{ steps.cache_new.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: |
          install.packages("remotes")
          install.packages("rsconnect")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("pkgdown")
        shell: Rscript {0}

      - name: Build
        run: npm build

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}


