# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_ACTIVATE_PROJECT: TRUE
      R_LIBS_USER: ~/Library/Application Support/renv
      GITHUB_ACTION: TRUE
      CENSUS_API_KEY: ${{ secrets.CENSUS_KEY }} 
      
# Got the renv setup advice from: https://github.com/r-lib/actions/tree/v2/setup-renv. 
# But not sure if this is necessary nor how to use it.        
      
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      
      # Very annoying that just compiling the packages does not work easily. Would probably
      # be better off using unbuntu and r2u. In the meantime, we need to hack arnound so
      # that problematic packages like sf compile. We definiately need gdal and sqlite3 to
      # be installed ahead of time.
 
      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config
          brew install gdal
          brew install sqlite
          
      - uses: r-lib/actions/setup-renv@v2
      - uses: r-lib/actions/setup-pandoc@v2    
        with:
          cache-version: 2
          extra-packages: |
            any::renv
            any::rcmdcheck
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}


