# Below is the standard "check-release" Github Actions from the nice
# folks at r-libs. It works fine. The problem is that I really want
# to use renv with this package. But, if you do, you need to use
# setup-renv instead of setup-r-dependencies, obviously. The problem
# with that is that setup-renv seems unable to work with rstanarm, and
# maybe other packages. Either it does not build at all or, if it does,
# the cache stops working. Despite many hours of work, and Q/A with
# Posit Community, I could not get it to function. So, no renv for
# this package.

# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
